[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://SrijanDev.netlify.app"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"
